### ISSUE TITLE
Looks like issue on ts

### ISSUE THREAD

**Issue by GuFFy12** [IceTank/mineflayer-item-map-downloader#3]
![image](https://user-images.githubusercontent.com/49491499/203843885-397e8f1f-42c7-4aa9-9ebe-c75aad350880.png)
probably extend of mineflayer events doesn't work correctly

**Comment by GuFFy12** [comment]
...
![image](https://user-images.githubusercontent.com/49491499/203844275-428f45c7-a046-4671-83ab-b86bdf6ac14a.png)

**Comment by GuFFy12** [comment]
oh, my mistake. 

import Map from 'mineflayer-item-map-downloader';
bot.loadPlugin(Map.mapDownloader);

**Comment by IceTank** [comment]
Fixed with version 1.1.1
